import Head from "next/head";
import Card from "~/components/Card";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Geotastic Game Countdown</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen bg-slate-900 p-4">
        <Card />
      </main>
    </>
  );
}
